[settings]
max-players = 100
offline-mode = false

[bind]
host = "0.0.0.0"
port = 5520

[servers]
lobby = "127.0.0.1:5521"
survival = "127.0.0.1:5522"

# The server order when a player logs in
join-order = ["lobby", "survival"]
