[settings]
max-players = 100
offline-mode = false
join-order = ["lobby", "survival"]

[bind]
host = "0.0.0.0"
port = 5520

[servers.lobby]
host = "127.0.0.1"
port = 5521

[servers.survival]
host = "127.0.0.1"
port = 5522
